# Generated by Django 3.2 on 2021-05-08 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mealtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Spheres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.quality')),
                ('sphere_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.spheres')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.quality')),
                ('sphere_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.spheres')),
            ],
        ),
        migrations.CreateModel(
            name='Spheres_weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphere_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.spheres')),
            ],
        ),
        migrations.CreateModel(
            name='Fun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.quality')),
                ('sphere_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.spheres')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('calorific', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mealtime_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.mealtime')),
                ('quality_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.quality')),
                ('sphere_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.spheres')),
            ],
        ),
    ]
