# Generated by Django 3.2 on 2021-05-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spheres_weight',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
