# Generated by Django 3.2 on 2021-05-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Месячный доход'),
        ),
    ]
