# Generated by Django 3.2 on 2021-05-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_userdata_monthly_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='apartment_costs',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Расходы на оплату жилья, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='credit_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кредитный платеж, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='education_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Плата за обучение, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='family_number',
            field=models.IntegerField(null=True, verbose_name='Количество членов семьи'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='food_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет питание, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='food_weight',
            field=models.IntegerField(null=True, verbose_name='Удельный вес сферы "Питание", %'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='fun_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет развлечения, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='fun_weight',
            field=models.IntegerField(null=True, verbose_name='Удельный вес сферы "Развлечения", %'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Месячный бюджет, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ежемесячный доход, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='other_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прочие расходы, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sport_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет спорт, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sport_weight',
            field=models.IntegerField(null=True, verbose_name='Удельный вес сферы "Спорт", %'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='transport_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет транспорт, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='transport_weight',
            field=models.IntegerField(null=True, verbose_name='Удельный вес сферы "Транспорт", %'),
        ),
    ]
