# Generated by Django 3.2 on 2021-05-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210523_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Питание', 'verbose_name_plural': 'Питание'},
        ),
        migrations.AlterModelOptions(
            name='fun',
            options={'verbose_name': 'Развлечение', 'verbose_name_plural': 'Развлечения'},
        ),
        migrations.AlterModelOptions(
            name='mealtime',
            options={'verbose_name': 'Прием пищи', 'verbose_name_plural': 'Приемы пищи'},
        ),
        migrations.AlterModelOptions(
            name='quality',
            options={'verbose_name': 'Качество жизни', 'verbose_name_plural': 'Качество жизни'},
        ),
        migrations.AlterModelOptions(
            name='spheres',
            options={'verbose_name': 'Сфера жизни', 'verbose_name_plural': 'Сферы жизни'},
        ),
        migrations.AlterModelOptions(
            name='spheres_weight',
            options={'verbose_name': 'Вес сферы', 'verbose_name_plural': 'Веса сфер'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Спорт', 'verbose_name_plural': 'Спорт'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорт'},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'Данные пользователя', 'verbose_name_plural': 'Данные пользователя'},
        ),
        migrations.AlterField(
            model_name='userdata',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Ежемесячный доход, руб.'),
        ),
    ]
