# Generated by Django 3.2 on 2021-05-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210529_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='food_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Бюджет питание, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='fun_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Бюджет развлечения, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Месячный бюджет, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ежемесячный доход, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sport_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Бюджет спорт, руб.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='transport_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Бюджет транспорт, руб.'),
        ),
    ]
