# Generated by Django 3.2 on 2021-05-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_userdata_food_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='food_weight',
            field=models.IntegerField(default=55, null=True, verbose_name='Удельный вес сферы "Питание", %'),
        ),
    ]
